### ISSUE TITLE
Support for observables and promises

### ISSUE THREAD

**Issue by sheerun** [apollographql/graphql-anywhere#11]
I ask since it's not mentioned in the readme. Does this library support Promises / Observables returned from resolve function. I imagine this could be useful for asynchronous fetching / observing objects, like redux store.

```
const resolver = (fieldName, root) => observeChild(root, fieldName);
```

```
const resolver = (fieldName, root) => fetch('/api/' + fieldName);
```

**Comment by stubailo** [comment]
It doesn't support that, since it's currently targeted at resolving data that is already available on the client.

However, I'd definitely be in favor of adding it! If you have a plan for where it would go, let's talk about it.

I originally thought it could be implemented completely as part of the ResultMapper but that turned out to be harder than expected because you need to traverse nested arrays of promises. Here's how far I got: https://github.com/apollostack/graphql-anywhere/blob/596f4c446da4db04ca77a180f3aa2c4f2426951c/test/mapper.ts#L12

**Comment by sheerun** [comment]
Implementing it in `graphql` would be probably easier. I think first good step is to add async/await support to this project with `typescript@next` (it supports es5).

I tried to do so, but I've got some typing errors.. Could you help?

**Comment by stubailo** [comment]
> I think first good step is to add async/await support to this project with typescript@next (it supports es5).

Which version is that? If you open a PR I can try to address the type errors.

**Comment by helfer** [comment]
@sheerun this could be an interesting project for our [contributor hack week](https://dev-blog.apollodata.com/save-the-date-apollo-contributor-week-eef66d09f0e6). Let me know if you're interested in doing it 🙂

**Comment by sheerun** [comment]
at least I can try :)

**Comment by gregory-h** [comment]
Also interested +1

**Comment by stubailo** [comment]
Thanks for opening this issue! We've moved the repo here: https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere

We're building async/promise support there! https://github.com/apollographql/apollo-client/pull/2670
