### ISSUE TITLE
Support `operationName` for queries with multiple named operations.

### ISSUE THREAD

**Issue by erydo** [apollographql/graphql-anywhere#34]
GraphQL documents with multiple named operations accept an `operationName` parameter (in addition to `query` and `variables`) to select the operation to run and return. 

https://github.com/facebook/graphql/blob/e1dd45286e83cea73b7b071dc14e9f4dc5208ace/spec/Section%206%20--%20Execution.md#executing-requests

**Comment by stubailo** [comment]
That's a good point - I was intending to match the signature of `graphql` but looks like I missed the `operationName` argument! Honestly it feels like we should change the arguments to use keywords instead of positional arguments, even though it would be cute if we have the same argument list as GraphQL.js...

**Comment by stubailo** [comment]
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere
